CREATE TABLE estate (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50),
    category VARCHAR(50),
    cost int,
    condition VARCHAR(50),
    acquisition_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    added_by_user VARCHAR(50)
);
