CREATE TABLE inventory_card (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    estate_id int,
    inventory_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    inventory_officer VARCHAR(255),
    notes VARCHAR(255),
    location VARCHAR(100),
    status VARCHAR(100),
    FOREIGN KEY (estate_id) REFERENCES estate(id)
);