CREATE TABLE users (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50),
    password VARCHAR(50),
    role VARCHAR(50),
    email VARCHAR(255),
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    added_by_user VARCHAR(50)
);
